Repository WildCodeSchool/orleans-0219-php-lavoliere, pull requests merged in 2019-06, with the labels that each got.

#36 S01 us02 header
  assets/scss/app.scss
  templates/index/index.html.twig
Labels: Reviewed by PO

#37 S01 us04 form contact
  .env
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/index.scss
  config/packages/twig.yaml
  src/Controller/IndexController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  templates/_footer.html.twig
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/emails/contact.html.twig
  templates/index/index.html.twig
  templates/visitorLayout.html.twig
Labels: Correction DONE, Reviewed by PO

#47 S01 us06 farm index
  assets/images/image_farm.jpg
  assets/images/image_gite1.jpg
  assets/images/image_gite2.jpg
  assets/images/image_whoFarm.jpeg
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/index.scss
  symfony.lock
  templates/index/index.html.twig
Labels: Correction DONE, Reviewed by PO

#35 S01 us07 map index
  assets/images/image_map_icon.png
  assets/js/index.js
  assets/scss/app.scss
  assets/scss/index.scss
  templates/base.html.twig
  templates/index/index.html.twig
  templates/visitorLayout.html.twig
  webpack.config.js
Labels: Correction DONE, Reviewed by PO

#52 S01 us13 bouton showcase
  assets/scss/_vars.scss
  assets/scss/index.scss
  templates/index/index.html.twig
Labels: Correction DONE, Reviewed by PO

#53 S01 us08 actualites
  src/Controller/EventController.php
  src/Controller/IndexController.php
  src/DataFixtures/EventFixtures.php
  src/Entity/Event.php
  src/Form/EventType.php
  src/Repository/EventRepository.php
  src/Repository/ProductRepository.php
  templates/event/_delete_form.html.twig
  templates/event/_form.html.twig
  templates/event/edit.html.twig
  templates/event/index.html.twig
  templates/event/new.html.twig
  templates/event/show.html.twig
  templates/index/index.html.twig
Labels: Ready to merge

#59 S01 us02 header fix 01
  assets/scss/index.scss
  templates/index/index.html.twig
Labels: Reviewed by PO

#63 S01 us09 address hours index
  assets/scss/app.scss
  assets/scss/index.scss
  templates/index/index.html.twig
Labels: Correction DONE, Reviewed by PO

#68 S01 us16 admin category
  assets/images/icon_delete.png
  assets/images/icon_edit.png
  src/Controller/Admin/CategoryController.php
  src/Entity/Category.php
  src/Form/CategoryType.php
  src/Repository/CategoryRepository.php
  templates/adminLayout.html.twig
  templates/category/_delete_form.html.twig
  templates/category/_form.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/category/new.html.twig
  templates/category/show.html.twig
Labels: Reviewed by PO

#71 S01 us17 collapse event
  assets/scss/index.scss
  templates/index/index.html.twig
Labels: Reviewed by PO

#73 S01 us19 admin category new
  assets/scss/admin.scss
  assets/scss/app.scss
  src/Controller/Admin/CategoryController.php
  src/Entity/Category.php
  src/Form/CategoryType.php
  templates/category/_form.html.twig
  templates/category/index.html.twig
Labels: Reviewed by PO

#70 S01 us18 banner
  assets/images/image_banner.jpg
  assets/images/logo_voliere_complet.png
  assets/scss/index.scss
  templates/index/index.html.twig
Labels: Ready to merge

#72 S01 us14 week basket
  assets/images/image_week_basket.jpg
  assets/scss/_vars.scss
  assets/scss/index.scss
  phpstan.neon
  src/Controller/IndexController.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/ProductFixtures.php
  src/Entity/Category.php
  src/Entity/Product.php
  templates/index/index.html.twig
Labels: Ready to merge

#87 S01 us01 navbar user fix
  assets/images/logoTest.png
  assets/js/index.js
  assets/scss/app.scss
  templates/_navbar.html.twig
Labels: Reviewed by PO

#85 fix bootstrap actualités
  templates/index/index.html.twig
Labels: Ready to merge, Reviewed by PO

#86 S01 us12 listing page produits
  assets/scss/app.scss
  assets/scss/catalog.scss
  assets/scss/index.scss
  src/Controller/CatalogController.php
  templates/catalog/index.html.twig
Labels: Reviewed by PO

#91 S01 us22 collapse contact
  assets/js/index.js
  assets/scss/index.scss
  templates/_navbar.html.twig
  templates/index/index.html.twig
Labels: Reviewed by PO

#93 S01 us17 collapse event
  assets/scss/index.scss
  templates/index/index.html.twig
Labels: Reviewed by PO

#96 us24 index graphism fix
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/index.scss
  src/DataFixtures/ProductFixtures.php
  templates/index/index.html.twig
Labels: Reviewed by PO

#97 S01 us25 login page
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/log.scss
  config/packages/security.yaml
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthenticator.php
  templates/_navbar.html.twig
  templates/security/login.html.twig
Labels: Reviewed by PO

#104 add header week basket
  assets/scss/catalog.scss
  src/Controller/CatalogController.php
  templates/catalog/index.html.twig
Labels: Reviewed by PO

#98 Fix 01 flash position
  assets/scss/_vars.scss
  assets/scss/app.scss
  composer.json
  symfony.lock
  templates/_navbar.html.twig
Labels: Correction DONE

#105 S02 us28 admin products
  assets/scss/admin.scss
  src/Controller/Admin/ProductController.php
  src/Repository/ProductRepository.php
  templates/product/index.html.twig
Labels: Reviewed by PO

#106 Fix symfony4.3
  composer.json
  composer.lock
  symfony.lock
Labels: Reviewed by PO

#110 change js code position for color navbar change on scroll
  assets/js/app.js
  assets/js/index.js
Labels: Reviewed by PO

#111 S01 us23 delivery farmpage
  assets/images/background-pattern_1.jpg
  assets/images/image_cagette.png
  assets/scss/farm.scss
  src/Controller/OurFarmController.php
  src/DataFixtures/LocationFixtures.php
  src/Entity/Location.php
  src/Repository/LocationRepository.php
  templates/our_farm/index.html.twig
Labels: Correction DONE, Reviewed by PO

#121 S01 us31 header farmpage
  assets/images/image_header_farm.jpg
  assets/scss/farm.scss
  templates/our_farm/index.html.twig
Labels: Ready to merge

#122 S02 us10 inscription
  assets/scss/_vars.scss
  assets/scss/log.scss
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
  templates/security/login.html.twig
Labels: Reviewed by PO

#123 FIX_MAP_INDEX
  assets/js/app.js
  assets/js/index.js
Labels: Reviewed by PO

#124 fix scss for conflict with homepage
  assets/scss/catalog.scss
  templates/catalog/index.html.twig
  templates/visitorLayout.html.twig
Labels: Reviewed by PO

#125 add links and navbar and change css
  assets/scss/app.scss
  templates/_navbar.html.twig
Labels: Reviewed by PO

#133 Fix sass and card in page product
  assets/scss/catalog.scss
  templates/catalog/index.html.twig
Labels: Reviewed by PO

#138 FIX_CONDITIONS_NO_PRODUCTS_NO_IMAGE_#136
  assets/images/image_product_default.jpg
  templates/index/index.html.twig
Labels: Reviewed by PO

#139 Dev to Master
  assets/images/background-pattern_1.jpg
  assets/images/image_cagette.png
  assets/images/image_header_farm.jpg
  assets/images/image_product_default.jpg
  assets/js/app.js
  assets/js/index.js
  assets/scss/_vars.scss
  assets/scss/admin.scss
  assets/scss/app.scss
  assets/scss/catalog.scss
  assets/scss/farm.scss
  assets/scss/index.scss
  assets/scss/log.scss
  composer.json
  composer.lock
  config/packages/security.yaml
  src/Controller/Admin/ProductController.php
  src/Controller/CatalogController.php
  src/Controller/OurFarmController.php
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/DataFixtures/LocationFixtures.php
  src/DataFixtures/ProductFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Location.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Repository/LocationRepository.php
  src/Repository/ProductRepository.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  templates/_navbar.html.twig
  templates/catalog/index.html.twig
  templates/index/index.html.twig
  templates/our_farm/index.html.twig
  templates/product/index.html.twig
  templates/registration/register.html.twig
  templates/security/login.html.twig
  templates/visitorLayout.html.twig
Labels: Reviewed by PO

#135 S01 us11 layout cart
  assets/scss/app.scss
  assets/scss/cart.scss
  src/Controller/CartController.php
  templates/_navbar.html.twig
  templates/cart/index.html.twig
Labels: Correction DONE, Reviewed by PO

#141 S02 us30 history farmpage
  assets/images/image_history_farmpage_2.png
  assets/images/picto_farm_history_1.png
  assets/images/picto_farm_history_2.png
  assets/images/picto_farm_history_3.png
  assets/images/picto_farm_history_4.png
  assets/scss/farm.scss
  templates/our_farm/index.html.twig
Labels: Reviewed by PO

#142 S02 us29 admin product new
  .gitignore
  assets/js/admin.js
  assets/scss/admin.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  src/Entity/Product.php
  src/Form/ProductType.php
  symfony.lock
  templates/adminLayout.html.twig
  templates/base.html.twig
  templates/catalog/index.html.twig
  templates/index/index.html.twig
  templates/product/_form.html.twig
  templates/product/index.html.twig
  templates/product/new.html.twig
  webpack.config.js
Labels: Changes requested

#147 S02 us34 admin product delete
  templates/product/index.html.twig
Labels: Changes requested

#151 S02 us32 fogotten password
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/log.scss
  composer.lock
  config/services.yaml
  src/Controller/ResetPasswordController.php
  src/Entity/User.php
  src/Form/RequestPasswordType.php
  src/Form/ResettingPasswordType.php
  src/Service/MailerService.php
  templates/reset_password/change_password.html.twig
  templates/reset_password/request_password.html.twig
  templates/reset_password/reset_password_mail.html.twig
  templates/security/login.html.twig
Labels: Reviewed by PO

#154 FIX_FR_ROUTE#153
  src/Controller/Admin/CategoryController.php
  src/Controller/Admin/ProductController.php
  src/Controller/CatalogController.php
  src/Controller/EventController.php
  src/Controller/OurFarmController.php
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
Labels: Reviewed by PO

#155 Fix card log #152
  assets/scss/_vars.scss
  assets/scss/log.scss
  src/Controller/ResetPasswordController.php
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
  templates/reset_password/change_password.html.twig
  templates/reset_password/request_password.html.twig
  templates/security/login.html.twig
  translations/security.en.yaml
Labels: Reviewed by PO

#161 S03 us39 my account
  assets/images/logo_logout.png
  assets/images/logo_modify.png
  assets/images/logo_order.png
  assets/images/logo_password.png
  assets/scss/app.scss
  assets/scss/my_account.scss
  src/Controller/AccountController.php
  templates/_navbar.html.twig
  templates/account/index.html.twig
Labels: Reviewed by PO

#162 S03 us37 delete product from cart
  assets/scss/cart.scss
  src/Controller/CartController.php
  templates/cart/_delete_form.html.twig
  templates/cart/index.html.twig
Labels: Reviewed by PO

#166 S03 us35 gite farmpage
  assets/images/farmpage/image_gite_1.jpg
  assets/images/farmpage/image_gite_2.jpg
  assets/images/farmpage/image_gite_4.jpg
  assets/images/farmpage/image_gite_6.jpg
  assets/images/farmpage/picto_farm_bed.png
  assets/images/farmpage/picto_farm_kitchen.png
  assets/images/farmpage/picto_farm_microwave.png
  assets/images/farmpage/picto_farm_people.png
  assets/images/farmpage/picto_farm_tv.png
  assets/images/farmpage/picto_farm_wifi.png
  assets/images/image_gitedefrance.png
  assets/scss/farm.scss
  templates/our_farm/index.html.twig
Labels: Reviewed by PO

#177 S03 us43 change password
  assets/scss/log.scss
  src/Controller/AccountController.php
  src/Form/ChangePasswordType.php
  templates/account/change_password.html.twig
  templates/account/index.html.twig
Labels: Ready to merge

#159 Us03 us38 page livraison
  .gitignore
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/order.scss
  config/packages/security.yaml
  src/Controller/OrderController.php
  templates/order/delivery.html.twig
Labels: Ready to merge, Reviewed by PO

#182 FIX_OPTIMIZATION_CONTACT_FORM#178
  config/services.yaml
  src/Controller/IndexController.php
Labels: Reviewed by PO

#191 Fix farm index
  assets/images/image_farm.jpg
  assets/images/image_ferme_1.jpg
  assets/images/image_gite1.jpg
  assets/images/image_gite2.jpg
  assets/images/image_whoFarm.jpeg
  assets/scss/index.scss
  templates/index/index.html.twig
Labels: Reviewed by PO

#185 S03_US45_ADMIN_INDEX_EVENT
  assets/scss/admin.scss
  src/Controller/Admin/EventController.php
  templates/event/index.html.twig
Labels: Reviewed by PO

#194 FIX_HEADER_CHANGE_PASSWOR#192
  assets/scss/my_account.scss
  src/Controller/AccountController.php
  templates/account/change_password.html.twig
Labels: Reviewed by PO

#204 fix price on index.html and catalog.html
  templates/catalog/index.html.twig
  templates/index/index.html.twig
Labels: Reviewed by PO

#184 fonctionnalité "ajouter au panier"
  assets/scss/cart.scss
  src/Controller/CartController.php
  src/Controller/CatalogController.php
  src/Controller/IndexController.php
  src/Entity/CartProduct.php
  src/Service/OrderService.php
  templates/cart/_delete_form.html.twig
  templates/cart/index.html.twig
  templates/catalog/index.html.twig
  templates/index/index.html.twig
Labels: Correction DONE, Reviewed by PO

#193 S03 us46 admin new event
  .gitignore
  assets/js/admin.js
  assets/scss/admin.scss
  config/packages/vich_uploader.yaml
  src/Controller/Admin/EventController.php
  src/Entity/Event.php
  src/Form/EventType.php
  templates/event/_form.html.twig
  templates/event/index.html.twig
  templates/event/new.html.twig
Labels: Reviewed by PO

#199 Fix licking index
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/index.scss
  package.json
  templates/index/index.html.twig
  yarn.lock
Labels: Reviewed by PO

#201 Fix weekbasket err 500 if dbb empty
  src/Controller/IndexController.php
Labels: Reviewed by PO

#206 add multiplateforms favicons
  assets/images/favIcon/android-chrome-192x192.png
  assets/images/favIcon/android-chrome-512x512.png
  assets/images/favIcon/apple-touch-icon.png
  assets/images/favIcon/browserconfig.xml
  assets/images/favIcon/favicon-16x16.png
  assets/images/favIcon/favicon-32x32.png
  assets/images/favIcon/favicon.ico
  assets/images/favIcon/mstile-150x150.png
  assets/images/favIcon/safari-pinned-tab.svg
  assets/images/favIcon/site.webmanifest
  templates/base.html.twig
Labels: Reviewed by PO

#198 S03 us 40 page livraison selection
  .env
  assets/scss/_vars.scss
  assets/scss/order.scss
  config/services.yaml
  src/Controller/CartController.php
  src/Controller/OrderController.php
  src/DataFixtures/LocationFixtures.php
  src/Entity/Delivery.php
  src/Entity/Location.php
  src/Form/DeliveryType.php
  src/Service/OrderService.php
  templates/order/delivery.html.twig
Labels: Ready to merge

#217 fix js toggle contact
  assets/js/app.js
  templates/index/index.html.twig
Labels: Ready to merge

#205 change regex for prices assert
  src/Entity/Product.php
Labels: Reviewed by PO

#220 fix our_farm entity request
  templates/our_farm/index.html.twig
Labels: Reviewed by PO

#210 Fix us26 produits panier semaine
  assets/scss/catalog.scss
  templates/catalog/index.html.twig
Labels: Reviewed by PO

#218 S03 us49 page validation
  assets/scss/order.scss
  src/Controller/CartController.php
  src/Controller/OrderController.php
  src/Entity/CartProduct.php
  src/Entity/Delivery.php
  src/Service/LocationService.php
  src/Service/OrderService.php
  templates/order/delivery.html.twig
  templates/order/validation.html.twig
Labels: Reviewed by PO

#223 Fix productspage
  templates/catalog/index.html.twig
Labels: Reviewed by PO

#228 S03_US48_ADMIN_INDEX
  assets/images/logo_categories.png
  assets/images/logo_events.png
  assets/images/logo_products.png
  assets/scss/admin.scss
  src/Controller/Admin/AdminController.php
  templates/admin/index.html.twig
Labels: Reviewed by PO

#224 S03 us51 cart count
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/order.scss
  config/packages/twig.yaml
  src/Controller/OrderController.php
  src/Service/OrderService.php
  templates/_navbar.html.twig
  templates/_navbar_cart_counter.html.twig
Labels: Ready to merge, Reviewed by PO

#230 S03 us54 admin navbar
  assets/scss/admin.scss
  templates/adminLayout.html.twig
Labels: Ready to merge, Reviewed by PO

#234 S03 us55 admin location index
  src/Controller/Admin/LocationController.php
  src/Form/LocationType.php
  templates/location/_delete_form.html.twig
  templates/location/_form.html.twig
  templates/location/edit.html.twig
  templates/location/index.html.twig
  templates/location/new.html.twig
  templates/location/show.html.twig
Labels: Reviewed by PO

#222 S03 us50 category productpage
  .env
  assets/scss/catalog.scss
  config/services.yaml
  src/Controller/CatalogController.php
  src/Repository/CategoryRepository.php
  templates/catalog/index.html.twig
Labels: Ready to merge, Reviewed by PO

#245 Fix index#242
  assets/scss/index.scss
  templates/_footer.html.twig
  templates/_navbar.html.twig
  templates/index/index.html.twig
  templates/our_farm/index.html.twig
Labels: Reviewed by PO

#248 fix admin products errors on origin
  templates/product/index.html.twig
Labels: Reviewed by PO

#250 fix price on week basket
  templates/catalog/index.html.twig
Labels: Reviewed by PO

#251 add modal for legal mentions
  assets/scss/_footer.scss
  templates/_footer.html.twig
Labels: Reviewed by PO

#254 Fix admin#246
  src/Entity/Event.php
  src/Form/CategoryType.php
  src/Form/EventType.php
  templates/category/_form.html.twig
  templates/event/_form.html.twig
  templates/event/edit.html.twig
  templates/event/index.html.twig
Labels: Reviewed by PO

#253 FIX_FORGOTTEN_PASSWORD#252
  src/Controller/ResetPasswordController.php
  templates/reset_password/reset_password_mail.html.twig
Labels: Reviewed by PO

#256 stylize checkbox
  assets/scss/app.scss
  assets/scss/checkbox.scss
Labels: Reviewed by PO
