Repository WildCodeSchool/orleans-0219-php-lavoliere, pull requests merged in 2019-07, with the labels that each got.

#244 S03 us53 confirmation order
  src/Controller/Admin/PurchaseController.php
  src/Controller/OrderController.php
  src/Entity/CartProduct.php
  src/Entity/Purchase.php
  src/Entity/PurchaseProduct.php
  src/Entity/User.php
  src/Form/PurchaseType.php
  src/Repository/PurchaseProductRepository.php
  src/Repository/PurchaseRepository.php
  src/Service/OrderService.php
  templates/emails/UserPurchaseMail.html.twig
  templates/order/success.html.twig
  templates/order/validation.html.twig
  templates/purchase/_delete_form.html.twig
  templates/purchase/_form.html.twig
  templates/purchase/edit.html.twig
  templates/purchase/index.html.twig
  templates/purchase/new.html.twig
  templates/purchase/show.html.twig
Labels: Correction DONE, Reviewed by PO

#257 Fix s03 logo connected
  assets/js/app.js
  assets/scss/app.scss
  src/Controller/AccountController.php
  templates/_navbar.html.twig
  templates/_navbar_check_connected.html.twig
Labels: Reviewed by PO

#262 FIX_VICH_UPLOADER_ADMIN#261
  src/Entity/Event.php
  src/Entity/Product.php
Labels: Reviewed by PO

#255 S03 us52 spinner counter products
  assets/scss/_vars.scss
  assets/scss/index.scss
  templates/index/index.html.twig
Labels: Ready to merge, Reviewed by PO

#267 fix nullable field
  src/Entity/Event.php
Labels: Reviewed by PO

#258 S04 us58 user command history
  assets/scss/my_account.scss
  src/Controller/AccountController.php
  src/Repository/PurchaseRepository.php
  src/Service/OrderService.php
  templates/account/history.html.twig
  templates/account/index.html.twig
Labels: Ready to merge, Reviewed by PO

#271 Fix licking productspage
  assets/scss/app.scss
  assets/scss/catalog.scss
  templates/catalog/index.html.twig
Labels: Reviewed by PO

#243 S03 us36 cart quantity
  assets/scss/cart.scss
  src/Controller/CartController.php
  src/Controller/OrderController.php
  src/Entity/CartProduct.php
  src/Service/OrderService.php
  templates/account/history.html.twig
  templates/cart/_delete_form.html.twig
  templates/cart/index.html.twig
  templates/index/index.html.twig
  templates/order/delivery.html.twig
Labels: Correction DONE, Reviewed by PO

#272 US36_Ajax shopping cart
  assets/js/cart.js
  src/Controller/CartController.php
  templates/cart/index.html.twig
  webpack.config.js
Labels: Reviewed by PO

#273 S04 us64 admin purchase
  assets/scss/admin.scss
  src/Controller/Admin/PurchaseController.php
  src/Repository/PurchaseRepository.php
  templates/adminLayout.html.twig
  templates/purchase/_delete_form.html.twig
  templates/purchase/_form.html.twig
  templates/purchase/index.html.twig
  templates/purchase/show.html.twig
Labels: Reviewed by PO

#276 S04 us66 admin purchase selection
  src/Controller/Admin/PurchaseController.php
  src/Repository/PurchaseRepository.php
  templates/account/edit_account.html.twig
  templates/purchase/index.html.twig
Labels: Correction DONE

#278 S04 us67 add to cart spinner
  src/Controller/CatalogController.php
  src/Controller/IndexController.php
  src/Service/OrderService.php
  templates/catalog/index.html.twig
Labels: Reviewed by PO

#289 S04 us59 partner index
  src/Controller/Admin/PartnerController.php
  src/DataFixtures/PartnerFixtures.php
  src/Entity/Partner.php
  src/Form/PartnerType.php
  src/Repository/PartnerRepository.php
  templates/adminLayout.html.twig
  templates/partner/_delete_form.html.twig
  templates/partner/_form.html.twig
  templates/partner/edit.html.twig
  templates/partner/index.html.twig
  templates/partner/new.html.twig
  templates/partner/show.html.twig
Labels: Reviewed by PO

#297 Fix chrome problems
  assets/scss/_vars.scss
  assets/scss/index.scss
  templates/index/index.html.twig
Labels: Reviewed by PO

#299 Add path to the orders
  templates/admin/index.html.twig
Labels: Reviewed by PO

#300 fix label remember me
  templates/security/login.html.twig
Labels: Reviewed by PO

#291 Add apache-pack
  .gitignore
  composer.json
  composer.lock
  symfony.lock
Labels: Correction DONE, Reviewed by PO

#296 S04 us67 add to cart spinner cartpage
  assets/scss/cart.scss
  src/Controller/IndexController.php
  templates/cart/index.html.twig
  templates/catalog/index.html.twig
Labels: Correction DONE, Reviewed by PO

#298 S04 us68 calendrier admin
  src/Controller/Admin/CalendarController.php
  src/DataFixtures/MonthCalendarFixtures.php
  src/DataFixtures/PickingCalendarFixtures.php
  src/Entity/MonthCalendar.php
  src/Entity/PickingCalendar.php
  src/Form/CalendarType.php
  src/Repository/CalendarRepository.php
  src/Repository/MonthCalendarRepository.php
  templates/adminLayout.html.twig
  templates/calendar/_delete_form.html.twig
  templates/calendar/_form.html.twig
  templates/calendar/edit.html.twig
  templates/calendar/index.html.twig
  templates/calendar/new.html.twig
Labels: Correction DONE, Reviewed by PO

#302 fix_livraison header order / validation
  src/Controller/OrderController.php
  templates/order/delivery.html.twig
  templates/order/validation.html.twig
Labels: Reviewed by PO

#305 change description for category in product index admin
  templates/product/index.html.twig
Labels: Reviewed by PO

#281 S04 us65 daily mail
  composer.json
  composer.lock
  config/packages/twig_extensions.yaml
  src/Command/DailyMailCommand.php
  src/Repository/PurchaseRepository.php
  src/Service/DailyMailerService.php
  src/Service/OrderService.php
  symfony.lock
  templates/emails/dailyMail.html.twig
Labels: Ready to merge, Reviewed by PO

#301 add clients view for admin
  src/Controller/Admin/UserController.php
  src/Repository/UserRepository.php
  templates/adminLayout.html.twig
  templates/user/index.html.twig
Labels: Ready to merge, Reviewed by PO

#310 change buttons on order
  templates/cart/index.html.twig
  templates/order/delivery.html.twig
  templates/order/validation.html.twig
Labels: Reviewed by PO

#309 Back button login pages
  assets/scss/_vars.scss
  assets/scss/my_account.scss
  templates/account/change_password.html.twig
  templates/account/edit_account.html.twig
  templates/account/history.html.twig
Labels: Reviewed by PO

#312 add amdin link
  templates/_navbar.html.twig
Labels: Reviewed by PO

#313 fix date format on events admin page
  templates/event/index.html.twig
Labels: Reviewed by PO

#314 fix success button
  templates/order/success.html.twig
Labels: Reviewed by PO

#316 fix S04 history user
  templates/account/history.html.twig
Labels: Reviewed by PO

#317 S04 us70 pdf daily mail
  composer.json
  composer.lock
  src/Service/DailyMailerService.php
  src/Service/MailerService.php
  templates/emails/pdf_daily_mail.html.twig
Labels: Reviewed by PO

#318 Fix contact index
  assets/images/image_map_icon.png
  assets/js/index.js
  assets/scss/_vars.scss
  assets/scss/index.scss
  src/Form/ContactType.php
  templates/index/index.html.twig
Labels: Correction DONE, Reviewed by PO

#323 Fix farmpart index
  assets/scss/index.scss
  symfony.lock
  templates/index/index.html.twig
Labels: Reviewed by PO

#324 FIX_ROLE_USER_REGISTRATION
  src/Controller/RegistrationController.php
Labels: Reviewed by PO

#328 FIX_DATE_FR
  templates/index/index.html.twig
Labels: Reviewed by PO

#334 fix height position for markers
  assets/scss/app.scss
Labels: Reviewed by PO

#320 fix responsive
  assets/scss/index.scss
  templates/index/index.html.twig
Labels: Ready to merge, Reviewed by PO

#325 S04 us71 admin recipe index
  src/Controller/Admin/RecipeController.php
  src/DataFixtures/RecipeFixtures.php
  src/Entity/Recipe.php
  src/Repository/RecipeRepository.php
  templates/adminLayout.html.twig
  templates/recipe/index.html.twig
Labels: Correction DONE, Reviewed by PO

#322 Fix s04 cart
  assets/scss/cart.scss
  templates/cart/_delete_form.html.twig
  templates/cart/index.html.twig
Labels: Correction DONE, Reviewed by PO

#344 fix padding farmpage
  assets/scss/farm.scss
  templates/our_farm/index.html.twig
Labels: Reviewed by PO

#345 harmonization of titles
  templates/account/change_password.html.twig
  templates/account/edit_account.html.twig
  templates/account/history.html.twig
  templates/account/index.html.twig
  templates/cart/index.html.twig
  templates/order/delivery.html.twig
  templates/order/success.html.twig
  templates/order/validation.html.twig
Labels: Reviewed by PO

#346 Fix Footer
  assets/scss/_footer.scss
  assets/scss/_vars.scss
  templates/_footer.html.twig
Labels: Reviewed by PO

#343 S04 us74 admin recipe delete
  src/Controller/Admin/RecipeController.php
  src/Entity/Recipe.php
  templates/recipe/_delete_form.html.twig
  templates/recipe/_form.html.twig
  templates/recipe/edit.html.twig
  templates/recipe/index.html.twig
Labels: Correction DONE, Reviewed by PO

#347 S04 us75 pdf admin daily order
  src/Controller/Admin/AdminController.php
  src/Service/DailyMailerService.php
  templates/admin/index.html.twig
Labels: Reviewed by PO

#348 FIX_LINK_CART
  templates/cart/index.html.twig
Labels: Reviewed by PO

#354 Fix s04 redirection add to cart
  assets/js/app.js
  assets/js/catalog.js
  src/Controller/CatalogController.php
  src/Controller/IndexController.php
  templates/catalog/index.html.twig
  templates/index/index.html.twig
  webpack.config.js
Labels: Reviewed by PO

#353 S04 us77 flash msg admin
  assets/scss/admin.scss
  src/Controller/Admin/CalendarController.php
  src/Controller/Admin/CategoryController.php
  src/Controller/Admin/EventController.php
  src/Controller/Admin/LocationController.php
  src/Controller/Admin/PartnerController.php
  src/Controller/Admin/ProductController.php
  src/Controller/Admin/PurchaseController.php
  src/Controller/Admin/RecipeController.php
  templates/adminLayout.html.twig
  templates/base.html.twig
Labels: Reviewed by PO

#355 Fix admin
  assets/images/logo_calendar.png
  assets/images/logo_users.png
  assets/scss/admin.scss
  templates/admin/index.html.twig
  templates/adminLayout.html.twig
  templates/product/index.html.twig
  templates/purchase/index.html.twig
Labels: Reviewed by PO

#356 fix bugs on navbar
  templates/_navbar.html.twig
Labels: Reviewed by PO

#358 S04 us78 pdf each order
  src/Controller/Admin/PurchaseController.php
  src/Service/DailyMailerService.php
  templates/purchase/show.html.twig
Labels: Reviewed by PO

#359 Change routes names for french routes
  src/Controller/Admin/CalendarController.php
  src/Controller/Admin/PartnerController.php
  src/Controller/CartController.php
Labels: Reviewed by PO

#362 fix_S04_SUCCESS_ORDER
  assets/scss/my_account.scss
  templates/account/history.html.twig
  templates/order/delivery.html.twig
  templates/order/validation.html.twig
Labels: Reviewed by PO

#364 add linkedin
  templates/_footer.html.twig
Labels: Reviewed by PO

#363 Remove some useless method and views
  src/Controller/Admin/EventController.php
  src/Controller/Admin/LocationController.php
  src/Controller/Admin/PartnerController.php
  src/Controller/Admin/ProductController.php
  templates/category/show.html.twig
  templates/event/show.html.twig
  templates/location/show.html.twig
  templates/partner/show.html.twig
  templates/product/show.html.twig
Labels: Ready to merge, Reviewed by PO

#365 Fix style admin location
  templates/adminLayout.html.twig
  templates/location/edit.html.twig
  templates/location/index.html.twig
  templates/location/show.html.twig
Labels: Ready to merge, Reviewed by PO

#370 fix condition showcased while offline
  src/Controller/IndexController.php
Labels: Reviewed by PO

#371 Fix map fullscreen
  assets/js/index.js
  assets/scss/index.scss
Labels: Reviewed by PO

#366 S04 us58 calendar
  assets/images/hand.png
  assets/images/hand_green.png
  assets/images/nothing.png
  assets/images/tractor.png
  assets/js/index.js
  assets/scss/index.scss
  src/Controller/Admin/CalendarController.php
  src/Controller/IndexController.php
  src/Entity/PickingCalendar.php
  src/Repository/PickingCalendarRepository.php
  templates/index/index.html.twig
Labels: Correction DONE, Reviewed by PO

#378 fix recipe length
  templates/recipe/index.html.twig
Labels: Reviewed by PO

#373 S04_US80_ADMIN_PRODUCT_SEARCH
  assets/scss/admin.scss
  src/Controller/Admin/ProductController.php
  src/Repository/ProductRepository.php
  templates/product/index.html.twig
Labels: Correction DONE, Reviewed by PO

#381 fix size checkbox on mobile
  assets/scss/checkbox.scss
Labels: Reviewed by PO

#380 condition if empty bdd for catalog page
  src/Controller/CatalogController.php
  templates/catalog/index.html.twig
Labels: Reviewed by PO

#382 change button style
  assets/scss/_vars.scss
  assets/scss/index.scss
  templates/index/index.html.twig
Labels: Reviewed by PO

#367 S04 us76 recipe week basket
  assets/scss/_vars.scss
  assets/scss/index.scss
  src/Controller/CatalogController.php
  src/Controller/IndexController.php
  templates/index/index.html.twig
Labels: Correction DONE, Reviewed by PO

#383 fix typos
  src/Form/RecipeType.php
  templates/account/history.html.twig
  templates/index/index.html.twig
  templates/recipe/index.html.twig
Labels: Reviewed by PO

#384 Fix order cart
  templates/cart/_delete_form.html.twig
  templates/cart/index.html.twig
  templates/order/validation.html.twig
Labels: Reviewed by PO

#386 add text to the connexion page
  assets/scss/log.scss
  templates/security/login.html.twig
Labels: Reviewed by PO

#387 change checkbox name
  src/Form/CalendarType.php
Labels: Reviewed by PO

#388 Fix chrome things
  assets/scss/_vars.scss
  assets/scss/index.scss
  templates/index/index.html.twig
Labels: Reviewed by PO

#389 FIX_LOGO_USER
  assets/images/logo_users.png
Labels: Reviewed by PO

#391 change color style of nav
  assets/scss/catalog.scss
Labels: Reviewed by PO

#392 fix phone low res problem for cards
  templates/index/index.html.twig
Labels: Reviewed by PO

#385 Fix w3c
  assets/scss/app.scss
  templates/_footer.html.twig
  templates/account/change_password.html.twig
  templates/account/history.html.twig
  templates/catalog/index.html.twig
  templates/index/index.html.twig
  templates/our_farm/index.html.twig
Labels: Ready to merge, Reviewed by PO

#390 Fix calendar
  assets/scss/_vars.scss
  assets/scss/index.scss
  templates/index/index.html.twig
Labels: Ready to merge, Reviewed by PO

#395 fix table
  assets/scss/my_account.scss
  templates/account/history.html.twig
  templates/order/validation.html.twig
  templates/purchase/show.html.twig
Labels: Reviewed by PO

#396 add condition for empty week basket
  src/Controller/CatalogController.php
Labels: Reviewed by PO

#394 Error 404
  assets/images/errors/image_errors_5_N&B_2.jpg
  assets/scss/app.scss
  assets/scss/errors.scss
  templates/base.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
Labels: Reviewed by PO

#397 add migrations
  phpcs.xml.dist
  src/Migrations/Version20190705091955.php
Labels: Reviewed by PO

#400 fix prod bugs
  src/Controller/Admin/CalendarController.php
  src/Security/LoginFormAuthenticator.php
Labels: Reviewed by PO

#401 FIX_VICH_PATH
  config/packages/vich_uploader.yaml
  templates/event/index.html.twig
  templates/partner/index.html.twig
Labels: Reviewed by PO

#402 add errors
  templates/bundles/TwigBundle/Exception/error405.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: Reviewed by PO

#407 Change a target + bugs with recipe
  assets/scss/index.scss
  src/Controller/Admin/RecipeController.php
  templates/index/index.html.twig
Labels: Reviewed by PO

#408 Fix footer
  templates/_footer.html.twig
Labels: Reviewed by PO

#405 fix bug vich_uploader path prod
  config/packages/vich_uploader.yaml
  templates/event/index.html.twig
  templates/partner/index.html.twig
Labels: Reviewed by PO

#409 Fix img map
  assets/js/index.js
  config/packages/vich_uploader.yaml
  templates/event/index.html.twig
  templates/partner/index.html.twig
Labels: Reviewed by PO

#406 Fix_calendar_entity
  src/Entity/PickingCalendar.php
Labels: Reviewed by PO

#410 payment text bigger + fix padding + fix js
  assets/js/catalog.js
  assets/scss/order.scss
  templates/order/success.html.twig
  templates/order/validation.html.twig
Labels: Reviewed by PO

#411 Fix carousel
  assets/scss/farm.scss
  templates/our_farm/index.html.twig
Labels: Reviewed by PO

#412 fix button order
  assets/scss/_vars.scss
Labels: Reviewed by PO

#413 Fix error 404
  assets/images/errors/image_errors_404.jpg
  assets/scss/app.scss
  assets/scss/errors404.scss
  templates/bundles/TwigBundle/Exception/error404.html.twig
Labels: Reviewed by PO

#414 fix tel + navbar contact
  assets/scss/index.scss
  templates/_footer.html.twig
  templates/_navbar.html.twig
  templates/index/index.html.twig
Labels: Reviewed by PO

#416 Fix s05 carousel
  assets/js/farm.js
  assets/scss/farm.scss
  templates/our_farm/index.html.twig
  webpack.config.js
Labels: Correction DONE, Reviewed by PO

#417 Fix cart counter
  assets/js/cart.js
  src/Controller/CartController.php
Labels: Correction DONE, Reviewed by PO

#415 fix typos
  templates/adminLayout.html.twig
  templates/location/index.html.twig
  templates/product/index.html.twig
  templates/purchase/index.html.twig
  templates/recipe/index.html.twig
Labels: Reviewed by PO

#418 Fix product description
  assets/scss/_vars.scss
  assets/scss/catalog.scss
  templates/catalog/index.html.twig
  templates/index/index.html.twig
Labels: Reviewed by PO

#419 Fix jumbotron height catalog
  assets/scss/catalog.scss
Labels: Reviewed by PO

#422 fix_product_description
  assets/scss/_vars.scss
  templates/catalog/index.html.twig
  templates/index/index.html.twig
Labels: Reviewed by PO

#421 fix calendar
  src/Entity/PickingCalendar.php
Labels: Correction DONE, Reviewed by PO

#423 fix size input number
  assets/scss/cart.scss
  templates/cart/index.html.twig
Labels: Reviewed by PO

#424 Last fix graphism
  assets/scss/_vars.scss
  assets/scss/index.scss
  assets/scss/order.scss
  templates/order/delivery.html.twig
Labels: Reviewed by PO

#425 fix_condition_not_connected
  assets/scss/app.scss
  src/Controller/AccountController.php
Labels: Reviewed by PO

#426 add README for deployment
  README.md
Labels: Reviewed by PO

#428 fix_useless_pages
  templates/location/show.html.twig
  templates/purchase/edit.html.twig
  templates/purchase/new.html.twig
Labels: Reviewed by PO

#427 fix_titles
  templates/event/edit.html.twig
  templates/location/index.html.twig
  templates/user/index.html.twig
Labels: Reviewed by PO

#430 fix_optimization_week_basket
  src/Controller/CatalogController.php
  src/Controller/IndexController.php
Labels: Reviewed by PO

#431 Dev
  src/Controller/CatalogController.php
  src/Controller/IndexController.php
Labels: Reviewed by PO

#433 Change vich path
  config/packages/vich_uploader.yaml
  templates/event/index.html.twig
  templates/partner/index.html.twig
Labels: Reviewed by PO

#434 fix container in purchase show
  templates/purchase/show.html.twig
Labels: Reviewed by PO

#435 Small fixes
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/cart/index.html.twig
  templates/location/index.html.twig
  templates/order/validation.html.twig
Labels: Reviewed by PO

#436 FIX_MODAL_AND_EVENTS
  assets/scss/_vars.scss
  assets/scss/index.scss
Labels: Reviewed by PO

#437 Fix img product
  templates/product/edit.html.twig
Labels: Reviewed by PO

#438 Dev to master
  assets/scss/_vars.scss
  assets/scss/index.scss
  config/packages/vich_uploader.yaml
  templates/_footer.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/cart/index.html.twig
  templates/event/index.html.twig
  templates/location/index.html.twig
  templates/order/validation.html.twig
  templates/partner/index.html.twig
  templates/product/edit.html.twig
  templates/purchase/show.html.twig
Labels: Reviewed by PO

#440 Fix_calendar_w3c
  templates/index/index.html.twig
Labels: Reviewed by PO

#439 fix card product on index and catalog
  assets/scss/_vars.scss
  templates/catalog/index.html.twig
  templates/index/index.html.twig
Labels: Reviewed by PO

#441 Dev
  assets/scss/_vars.scss
  templates/catalog/index.html.twig
  templates/index/index.html.twig
Labels: Reviewed by PO

#443 fix flash alert and auth
  src/Controller/AccountController.php
  src/Form/ChangePasswordType.php
Labels: Reviewed by PO

#444 new button link on jumbotron
  assets/js/index.js
  assets/scss/index.scss
  templates/index/index.html.twig
Labels: Reviewed by PO

#445 Add mail when register
  src/Controller/RegistrationController.php
  templates/emails/registrationMail.html.twig
Labels: Reviewed by PO

#446 add invalid message in DeliveryType
  src/Form/DeliveryType.php
Labels: Reviewed by PO

#447 Change login redirection by roles
  src/Controller/SecurityController.php
  src/Security/LoginFormAuthenticator.php
Labels: Reviewed by PO

#449 change font-size card description
  assets/scss/_vars.scss
  templates/cart/index.html.twig
Labels: Reviewed by PO

#450 FIX_FORM
  src/Form/ChangePasswordType.php
  src/Form/ContactType.php
  src/Form/DeliveryType.php
  src/Form/EventType.php
  src/Form/LocationType.php
  src/Form/PartnerType.php
  src/Form/ProductType.php
  src/Form/RecipeType.php
  src/Form/RegistrationFormType.php
  src/Form/RequestPasswordType.php
  src/Form/ResettingPasswordType.php
  src/Form/UserInformationType.php
  templates/product/_form.html.twig
Labels: Ready to merge, Reviewed by PO

#448 FIX_RESET_PASSWORD
  src/Controller/ResetPasswordController.php
Labels: Correction DONE

#451 fix height cards delivery location
  assets/scss/farm.scss
  assets/scss/order.scss
  templates/our_farm/index.html.twig
Labels: Reviewed by PO

#452 fix inversedBy properties on PickingCalendar
  src/Entity/PickingCalendar.php
Labels: Reviewed by PO

#453 Fix size cards
  assets/scss/cart.scss
  templates/cart/index.html.twig
Labels: Reviewed by PO

#454 Add line with delivery place
  templates/emails/pdf_daily_mail.html.twig
Labels: Reviewed by PO

#455 add placeholder for safari and date range constraints
  src/Form/DeliveryType.php
Labels: Correction DONE, Ready to merge, Reviewed by PO

#458 change text for hosting
  templates/our_farm/index.html.twig
Labels: Reviewed by PO

#456 add cart on smartphone's widht navbar
  assets/scss/app.scss
  templates/_navbar.html.twig
Labels: Reviewed by PO

#461 Fix location collecte
  assets/scss/farm.scss
  assets/scss/order.scss
  templates/order/delivery.html.twig
  templates/our_farm/index.html.twig
Labels: Reviewed by PO

#462 FIX_PDF
  src/Command/DailyMailCommand.php
  src/Controller/Admin/AdminController.php
  src/Repository/PurchaseProductRepository.php
  src/Service/DailyMailerService.php
  templates/emails/dailyMail.html.twig
Labels: Reviewed by PO

#463 fix comments label on delivery order page
  src/Form/DeliveryType.php
Labels: Reviewed by PO

#464 Fix pdf date
  src/Repository/PurchaseProductRepository.php
  src/Service/DailyMailerService.php
Labels: Reviewed by PO

#465 Dev
  src/Command/DailyMailCommand.php
  src/Controller/Admin/AdminController.php
  src/Form/DeliveryType.php
  src/Repository/PurchaseProductRepository.php
  src/Service/DailyMailerService.php
  templates/emails/dailyMail.html.twig
Labels: Reviewed by PO

#466 add_pdf_by_date
  src/Controller/Admin/PurchaseController.php
  src/Repository/PurchaseProductRepository.php
  src/Service/DailyMailerService.php
  templates/emails/pdfMailByDateInterval.html.twig
  templates/purchase/index.html.twig
Labels: Reviewed by PO

#467 Dev to master
  src/Controller/Admin/PurchaseController.php
  src/Repository/PurchaseProductRepository.php
  src/Service/DailyMailerService.php
  templates/emails/pdfMailByDateInterval.html.twig
  templates/purchase/index.html.twig
Labels: Reviewed by PO
